language: objective-c
osx_image: xcode7.3
script:
  - set -o pipefail
  - xcodebuild test -scheme OptionalExtensions-Mac | xcpretty -c
  - xcodebuild test -scheme OptionalExtensions-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme OptionalExtensions-tvOS -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme OptionalExtensions-watchOS -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty -c
